name: daytistics
services:
  # database:
  #   image: postgres:16
  #   container_name: daytistics_database # Added explicit container name
  #   environment:
  #     POSTGRES_DB: daytistics_dev
  #     POSTGRES_USER: daytistics_user
  #     POSTGRES_PASSWORD: daytistics_pw
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data_dev:/var/lib/postgresql/data
  #   networks:
  #     - daytistics_network # Updated network reference

  # backend:
  #   # env_file:
  #   #   - ./backend/.env.example
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   container_name: daytistics_backend # Added explicit container name
  #   ports:
  #     - 8000:8000
  #     - 9229:9229
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     DATABASE_URL: postgresql://daytistics_user:daytistics_pw@daytistics_database:5432/daytistics_dev
  #   depends_on:
  #     - database
  #   networks:
  #     - daytistics_network # Updated network reference

  frontend:
    container_name: daytistics_frontend # Added explicit container name
    volumes:
      - ./frontend:/app
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # depends_on:
    #   - backend
    networks:
      - daytistics_network # Updated network reference

#   supabase:
#     container_name: daytistics_supabase # Added explicit container name
#     volumes:
#       - ./supabase:/app
#     build:
#       context: ./supabase
#       dockerfile: Dockerfile.dev
#     ports:
#       - 54321:54321
#       - 54322:54322
#       - 54323:54323
#       - 54324:54324
#       - 54325:54325
#     depends_on:
#       - backend
#     networks:
#       - daytistics_network # Updated network reference

#   docs:
#     container_name: daytistics_docs # Added explicit container name
#     volumes:
#       - ./docs:/app
#     build:
#       context: ./docs
#       dockerfile: Dockerfile.dev
#     ports:
#       - 4000:4000
#     networks:
#       - daytistics_network # Updated network reference

#   mailhog:
#     image: mailhog/mailhog:latest
#     container_name: mailhog
#     ports:
#       - "1025:1025" # SMTP server
#       - "8025:8025" # Web UI
#     networks:
#       - daytistics_network

# volumes:
#   postgres_data_dev:

networks:
  daytistics_network:
    name: daytistics_network
