services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_SUPABASE_URL=http://localhost:54321
      - NUXT_PUBLIC_SUPABASE_ANON_KEY=your-local-anon-key
    depends_on:
      - supabase

  supabase:
    build:
      context: ./supabase
      dockerfile: Dockerfile.dev
    volumes:
      - ./supabase:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "54321:54321"
      - "54323:54323"
    privileged: true
