services:
  frontend:
    build:
      context: ./daytistics
      dockerfile: Dockerfile.dev
    volumes:
      - ./daytistics:/app
    ports:
      - "3000:3000"
    networks:
      - daytistics_network

  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile.dev
    volumes:
      - ./docs:/app
    ports:
      - "5173:5173"
    networks:
      - daytistics_network

networks:
  daytistics_network:
    driver: bridge
    external: true
