FROM node:22

WORKDIR /app

COPY ./package.json /app/package.json

RUN npm install -g pnpm

RUN npm install -g @nestjs/cli

RUN pnpm install

COPY ./ /app

EXPOSE 8000

CMD ["pnpm", "run", "start:debug"]